import * as C from "Constants/index";

import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    router.push(C.About.ROUTE);
  }, [router]);

  return (
    <div>
      <Head>
        <title>Food Fight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body></body>
    </div>
  );
};

export default Home;
