import * as S from "Styles/index";

import type { NextPage } from "next";
import Head from "next/head";

import About from "pages/About";

interface HomeProps {}

const Home: NextPage = ({}: HomeProps) => {
  return (
    <S.Container>
      <Head>
        <title>Food Fight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Body>
        <About />
      </S.Body>
    </S.Container>
  );
};

export default Home;
