import type { NextPage } from "next";
import Head from "next/head";

import About from "pages/About";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Food Fight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <About />
      </body>
    </div>
  );
};

export default Home;
